//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.17 at 04:57:15 PM WET 
//


package jee.ensas.myagencyservice.daos;

import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agency", propOrder = {
        "id",
        "name",
        "location",
        "city",
        "idAgent",
        "latitude",
        "longitude"
})
@Data
@Document("agencies")
public class Agency {

    @XmlElement(required = true)
    protected String id;

    @XmlElement(required = true)
    protected String name;

    @XmlElement(required = true)
    protected String location;

    @XmlElement(required = true)
    protected String city;

    @XmlElement(required = true)
    protected String idAgent;

    @XmlElement(required = true)
    protected String latitude;

    @XmlElement(required = true)
    protected String longitude;

}
