//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.17 at 04:57:15 PM WET 
//


package jee.ensas.myagencyservice.daos;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAgencyByIdRequest }
     * 
     */
    public GetAgencyByIdRequest createGetAgencyByIdRequest() {
        return new GetAgencyByIdRequest();
    }

    /**
     * Create an instance of {@link GetAgencyByIdResponse }
     * 
     */
    public GetAgencyByIdResponse createGetAgencyByIdResponse() {
        return new GetAgencyByIdResponse();
    }

    /**
     * Create an instance of {@link Agency }
     * 
     */
    public Agency createAgency() {
        return new Agency();
    }

    /**
     * Create an instance of {@link GetAllAgenciesRequest }
     * 
     */
    public GetAllAgenciesRequest createGetAllAgenciesRequest() {
        return new GetAllAgenciesRequest();
    }

    /**
     * Create an instance of {@link GetAllAgenciesResponse }
     * 
     */
    public GetAllAgenciesResponse createGetAllAgenciesResponse() {
        return new GetAllAgenciesResponse();
    }

    /**
     * Create an instance of {@link AddAgencyRequest }
     * 
     */
    public AddAgencyRequest createAddAgencyRequest() {
        return new AddAgencyRequest();
    }

    /**
     * Create an instance of {@link AddAgencyResponse }
     * 
     */
    public AddAgencyResponse createAddAgencyResponse() {
        return new AddAgencyResponse();
    }

    /**
     * Create an instance of {@link UpdateAgencyRequest }
     * 
     */
    public UpdateAgencyRequest createUpdateAgencyRequest() {
        return new UpdateAgencyRequest();
    }

    /**
     * Create an instance of {@link UpdateAgencyResponse }
     * 
     */
    public UpdateAgencyResponse createUpdateAgencyResponse() {
        return new UpdateAgencyResponse();
    }

    /**
     * Create an instance of {@link DeleteAgencyRequest }
     * 
     */
    public DeleteAgencyRequest createDeleteAgencyRequest() {
        return new DeleteAgencyRequest();
    }

    /**
     * Create an instance of {@link DeleteAgencyResponse }
     * 
     */
    public DeleteAgencyResponse createDeleteAgencyResponse() {
        return new DeleteAgencyResponse();
    }

}
